---
apiVersion: v1
kind: Pod
metadata:
  name: petclinic
spec:
  containers:
    - image: yvak90/petclinic:1.0
      name: spc
      ports:
        - containerPort: 8080
          name: spchttpport
          protocol: TCP
