apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: spc
      version: "1.0"
  template:
    metadata:
      labels:
        app: spc
        version: "1.0"
    spec:
      containers:
        - image: yvak90/petclinic:1.0
          name: spc
          ports:
            - containerPort: 8080
              protocol: TCP
