apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gol-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: gol
      version: "1.0"
  template:
    metadata:
      labels:
        app: gol
        version: "1.0"
    spec:
      containers:
        - image: yvak90/gameoflife:1.0
          name: gol
          ports:
            - containerPort: 8080
              protocol: TCP
