---
apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
spec:
  containers:
    - image: yvak90/gameoflife:1.0
      name: gol
      ports:
        - containerPort: 8080
          name: golhttpport
          protocol: TCP
