FROM openjdk:11
LABEL author="ajay"
ADD https://s3.ap-south-1.amazonaws.com/aj.soft.bucket/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar /spring-petclinic-2.4.2.jar
EXPOSE 8080
CMD ["java", "-jar", "/spring-petclinic-2.4.2.jar"]

